Remove conan-server and masl-populate docker definitions; update masl-dev

diff --git a/docker/masl-dev/os-files/usr/local/bin/conan-publish b/docker/masl-dev/os-files/usr/local/bin/conan-publish
--- a/docker/masl-dev/os-files/usr/local/bin/conan-publish
+++ b/docker/masl-dev/os-files/usr/local/bin/conan-publish
@@ -1,7 +1,11 @@
 #!/bin/bash
 pid=$$
-conan remote login -p docker xtuml docker &&\
-conan create .  --format=json --build=missing "$@" > /tmp/${name}_create.json &&\
-conan list --graph=/tmp/${name}_create.json --graph-binaries=build --format=json > /tmp/${name}_pkglist.json &&\
-conan upload --list=/tmp/${name}_pkglist.json -r=xtuml -c &&\
+conan create . --format=json --build=missing "$@" >/tmp/${name}_create.json
+conan list --graph=/tmp/${name}_create.json --graph-binaries=build --format=json >/tmp/${name}_pkglist.json
+conan remote login -p ${ARTIFACTORY_TOKEN} xtuml ${ARTIFACTORY_USERNAME}
+if [[ $? == 0 ]]; then
+	conan upload --list=/tmp/${name}_pkglist.json -r=xtuml -c
+else
+	echo "$(tput setaf 1)Could not log in to remote server. Check that ARTIFACTORY_USERNAME and ARTIFACTORY_TOKEN are set.$(tput sgr0)"
+fi
 rm /tmp/${name}_*
